version: "3.8"
services:
  app:
    build:
      context: .
      args:
        DOCKER_TAG: ${DOCKER_TAG:-latest}
    image: $DOCKER_USERNAME/backendblogging:${DOCKER_TAG}
    ports:
      - "3010:3010"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - mynetwork
    command: sh -c "while ! nc -z postgres 5432; do sleep 1; done; npm start"

  postgres:
    image: postgres:latest
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mynetwork:
    driver: bridge