services:
  app:
    build:
      context: . 
      args:
        DOCKER_TAG: ${DOCKER_TAG:-latest}
    image: $DOCKER_USERNAME/backendblogging:${DOCKER_TAG}
    ports:
      - "3010:3010"
    depends_on:
      - appdb
    restart: on-failure
    env_file:
      - .env
    networks:
      - mynetwork
    command: ["./wait-for-it.sh", "appdb:5432", "--", "node", "build/server"]

  appdb:
    image: postgres:latest
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
      - appdb_data:/var/lib/postgresql/data
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  appdb_data: