services:
  server:
    image: server:latest
    container_name: backendblogging
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./server:/server
      - server-node-modules:/server/node_modules
    command: npm run start
    depends_on:
      database:
        condition: service_healthy

  database:
    image: database:latest
    container_name: ${DATABASE_HOST}
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - database-v:/var/lib/postgresql/data
    command: "-p ${DATABASE_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${DATABASE_PORT} -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  server-node-modules:
    name: "server-node-modules"
  database-v:
    name: "database-v"

