services:
  app:
    build:
      context: . 
      args:
        DOCKER_TAG: ${DOCKER_TAG:-latest}
    image: $DOCKER_USERNAME/backendblogging:${DOCKER_TAG}
    ports:
      - "3010:3010"
    depends_on:
      - appdb
    restart: on-failure
    networks:
      - mynetwork
    command: ["./wait-for-it.sh", "appdb:5432", "--", "node", "build/server"]
    environment:
      - PORT=${PORT}
      - ENV=${ENV}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - JWT_SECRET=${JWT_SECRET}

  appdb:
    image: postgres:latest
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
      - appdb_data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

networks:
  mynetwork:
    driver: bridge

volumes:
  appdb_data: