version: '3.8'

services:
  app:
    build:
      context: .
    image: $DOCKER_USERNAME/backendblogging:latest
    ports:
      - "3010:3010"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      mynetwork:
        aliases:
          - app
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - ./entrypoint.sh:/usr/app/entrypoint.sh:ro

  postgres:
    image: postgres:latest
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      mynetwork:
        aliases:
          - postgres

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: