version: "3.8"
services:
  app:
    build: .
    ports:
      - "3010:3010"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
    env_file:
      - .env
    ports:
      - "5432:5432"