version: "3.8"
services:
  app:
    build:
      context: .
      args:
        DOCKER_TAG: ${DOCKER_TAG:-latest}
    image: $DOCKER_USERNAME/backendblogging:${DOCKER_TAG}
    ports:
      - "3010:3010"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - mynetwork
    command: ["/usr/local/bin/wait-for-it.sh", "postgres:5432", "--", "node", "build/server"]

  postgres:
    image: postgres:latest
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
