name: Build and Push Docker Image with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  docker-compose-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD


      - name: Build and Start Services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Push Docker Images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml push
