name: Docker Compose Action

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PORT: ${{ secrets.PORT }}
      ENV: ${{ secrets.ENV }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "ENV=${{ secrets.ENV }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Images with Docker Compose
        run: docker-compose -f docker-compose.yml build

      - name: Tag Docker Image with 'latest'
        run: |
          IMAGE_ID=$(docker-compose -f docker-compose.yml images -q app)
          if [[ -z "$IMAGE_ID" ]]; then
            echo "No image ID found for 'app'. Cannot tag image."
            exit 1
          else
            docker tag $IMAGE_ID $DOCKER_USERNAME/backendblogging:latest
          fi

      - name: Push Docker Images with Docker Compose
        run: docker-compose -f docker-compose.yml push

      - name: Push 'latest' Tagged Image to Docker Hub
        run: docker push $DOCKER_USERNAME/backendblogging:latest