name: Docker Compose Action

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Start Services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Push Docker Images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml push

# name: Build and Push Docker Image with Docker Compose

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     env:
#       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Build and Push Docker Image

#         run: |
#           docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-blogging:latest \
#             --build-arg PORT=3010 \
#             --build-arg ENV=development \
#             --build-arg DATABASE_USER=${{ secrets.DATABASE_USER }} \
#             --build-arg DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
#             --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
#             --build-arg DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
#             --build-arg DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
#             --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" \
#             --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" \
#             .
#           docker push ${{ secrets.DOCKER_USERNAME }}/backend-blogging:latest

#   docker-compose-build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Log in to Docker Hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#       - name: Build and Start Services with Docker Compose
#         run: |
#           docker-compose -f docker-compose.yml up --build -d

#       - name: Push Docker Images with Docker Compose
#         run: |
#           docker-compose -f docker-compose.yml push
