name: Docker Compose Action

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PORT: ${{ secrets.PORT }}
      ENV: ${{ secrets.ENV }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DOCKER_TAG: latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "ENV=${{ secrets.ENV }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build Docker Image
        run: docker build --build-arg PORT=${{ secrets.PORT }} -t $DOCKER_USERNAME/blogging-back:${{ env.DOCKER_TAG }} .

      - name: Push Docker Image
        run: docker push $DOCKER_USERNAME/blogging-back:${{ env.DOCKER_TAG }}

      - name: Push 'latest' Tagged Image to Docker Hub
        run: docker tag $DOCKER_USERNAME/blogging-back:${{ env.DOCKER_TAG }} $DOCKER_USERNAME/blogging-back:latest && docker push $DOCKER_USERNAME/blogging-back:latest
