name: Build and Push Docker Image with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  docker-compose-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Start Services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: Push Docker Images with Docker Compose
        run: |
          docker-compose -f docker-compose.yml push